CC      = g++
CXXFLAGS  = -Wall -g -D_POSIX_SOURCE -D_BSD_SOURCE -std=c++14 -pedantic

.SUFFIXES: .c .cpp .o

.PHONY: all clean

all: RUL

RUL: RUL.o List.o Piece.o NetworkFlags.o PieceRotation.o

#dependencies#

clean:
	rm -f $(wildcard *.o)
	rm -f RUL
