CC      = gcc
CFLAGS  = -Wall -g -D_POSIX_SOURCE -D_BSD_SOURCE -std=c99 -pedantic 

.SUFFIXES: .c .o

.PHONY: all clean

all: RUL

RUL: RUL.o List.o Piece.o NetworkFlags.o PieceRotation.o

#dependencies#

clean:
	rm -f $(wildcard *.o)
	rm -f RUL
